version: '3.8'

services:
  twitch-integration:
    image: sidey383/twitch-integration:${TAG:-latest}
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/twitch_integration
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

      TWITCH_SECRET: ${TWITCH_SECRET:-big-secret!}
      TWITCH_ID: ${TWITCH_ID:-twitch-client-id}
      TWITCH_REDIRECT_URL: ${TWITCH_REDIRECT_URL:-http://localhost/oauth2/twitch/callback}
      TWITCH_CALLBACK_REDIRECT_URL: ${TWITCH_CALLBACK_REDIRECT_URL:-/profile?twitch=connected}
      TWITCH_WEBHOOK_URL: ${TWITCH_WEBHOOK_URL:-https://twitch.sidey383.ru/webhook/twitch}

      JWT_SECRET: ${JWT_SECRET:-YXNkZmF3ZHdhZmRBRkFTRkFXZHNmZ2dhc2dhc2Z3RVJScVdFUkh3ZXJ0ZmV3cg==}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-300000}

      MINECRAFT_RCON_HOST: ${MINECRAFT_RCON_HOST:-localhost}
      MINECRAFT_RCON_PORT: ${MINECRAFT_RCON_PORT:-25575}
      MINECRAFT_RCON_PASSWORD: ${MINECRAFT_RCON_PASSWORD:-password}

    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: twitch_integration
    ports:
      - "3306:3306"
    healthcheck:
      test: >
        mariadb -uroot -ppassword -e "SELECT 1;" twitch_integration
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: