spring:
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: file:src/main/resources/templates/
logging:
  level:
    org.springframework.security.oauth2: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
    ru.sidey383.twitch: DEBUG