spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/twitch_integration}
    username: ${SPRING_DATASOURCE_USERNAME:twitch-integration}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB106Dialect
  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${TWITCH_ID:twitch-client-clientId}
            client-secret: ${TWITCH_SECRET:big-clientSecret!}
            client-name: Twitch
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user:read:email,channel:read:redemptions
            webhook-uri: ${TWITCH_WEBHOOK_URL:https://twitch.sidey383.ru/webhook/twitch}
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://api.twitch.tv/helix/users
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            user-name-attribute: clientId

minecraft:
  rcon:
    host: ${MINECRAFT_RCON_HOST:localhost}
    port: ${MINECRAFT_RCON_PORT:25575}
    password: ${MINECRAFT_RCON_PASSWORD:password}
