spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/twitch_integration}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

twitch:
  secret: ${TWITCH_SECRET:big-secret!}
  id: ${TWITCH_ID:twitch-client-id}
  redirect-uri: ${TWITCH_REDIRECT_URL:http://localhost/oauth2/twitch/callback}
  callback-redirect-uri: ${TWITCH_CALLBACK_REDIRECT_URL:/profile?twitch=connected}
  webhook-uri: ${TWITCH_WEBHOOK_URL:https://twitch.sidey383.ru/webhook/twitch}


jwt:
  secret: YXNkZmF3ZHdhZmRBRkFTRkFXZHNmZ2dhc2Z3RVJScVdFUkh3ZXJ0ZmV3cg==
  expiration: 300000

minecraft:
  rcon:
    host: ${MINECRAFT_RCON_HOST:localhost}
    port: ${MINECRAFT_RCON_PORT:25575}
    password: ${MINECRAFT_RCON_PASSWORD:password}