# .github/workflows/docker-publish.yml
name: Docker Publish 📦

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Docker image via bootBuildImage
        run: ./gradlew bootBuildImage --no-daemon

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          VERSION=$(./gradlew -q printVersion) # see note
          echo "Pushing version $VERSION"
          docker tag sidey383/twitch-integration:${project.version} \
            ghcr.io/${{ github.repository_owner }}/twitch-integration:$VERSION
          docker tag sidey383/twitch-integration:${project.version} \
            ghcr.io/${{ github.repository_owner }}/twitch-integration:latest
          docker push ghcr.io/${{ github.repository_owner }}/twitch-integration:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/twitch-integration:latest
